services:
  - type: web
    name: news-aggregator
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn news_aggregator.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: MONGODB_URL
        value: mongodb+srv://vikash:vikash%40123@cluster0.cz6joof.mongodb.net/?appName=Cluster0

